spring:
  application:
    name: drone-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/drone_db}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    port: 5672
    template:
      observation-enabled: true
    listener:
      simple:
        observation-enabled: true

server:
  port: 8080

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, prometheus # Expose the health and prometheus endpoints
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: WARN
    org.example: INFO