spring:
  application:
    name: drone-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    port: 5672

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus # Expose the health and prometheus endpoints
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}